### ISSUE TITLE
Fulmar apparently doesn't work with the new macro expander.

### ISSUE THREAD

**Issue by LeifAndersen** [cwearl/fulmar#21] opened 2015-10-23 15:22 UTC
When I try to run fulmar with the new macro expander (currently using Racket from the source repo, version 6.3.0.2)

And I create the file:

```
#lang fulmar
```

I get the following error:
```
. rsrc/fulmar/main.rkt:39:13: require: identifier's binding is ambiguous
  context.:
  matching binding.:
  matching binding.: in: require
```

**Comment by michaelballantyne** [comment] 2015-11-18 23:00
Fixed by 4cf60699558b3bb28fa813443456993d1563bfb2

I was able to work around the problem, but I don't fully understand the cause of it. Thanks for checking out fulmar, Leif!

**Closed** 2015-11-18 23:02 UTC
